Fixes "Cannot read property 'split' of undefined"
Error: TypeError: Cannot read property 'split' of undefined
  at HtmlReport.writeDetailPage
(/node_modules/istanbul/lib/report/html.js:412:30)

Cause: source cache is shared by basePath and this mutation causes
report to not be able to look up code correctly.